### ISSUE TITLE
Add a global Minimum self delegation

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/cosmos-sdk#113]
## Summary

Add a global minimum self delegation parameter, similar to the minimum commission rate.

## Problem Definition

This isn't a big restriction, as limited validator slots already _effectively_ has this requirement. However this increases the costs to spam the number of validators. The number of validators active in the last $UNBONDING_PERIOD can have unfortunate impacts on efficiency when an app-chain's module has other amplification factors on the load caused by validators.

The base SDK has some amplification factor here, (state storage, historical signing info windows), but on brief skim nothing concerning, hence why it likely wasn't thought about before.

## Proposal

Add a global minimum self delegation parameter to the codebase. For Osmosis, I suggest making it something like 100 osmo, which makes attacks that concern me very infeasible.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ValarDragon** [comment]
If such a change is only enforced on MsgCreateValidator and MsgEditValidator, then we won't run into any issues with existing validators either.

**Comment by AlpinYukseloglu** [comment]
@ValarDragon Which file would this global minimum need to be declared in? I see that each `MsgCreateValidator` and `MsgEditValidator` have `MinSelfDelegation` fields, but I'm assuming this issue is trying to set a global minimum that these have to conform with.

**Comment by ValarDragon** [comment]
Register migration https://github.com/osmosis-labs/cosmos-sdk/blob/v0.45.0x-osmo-v7/x/staking/module.go#L143
Code for past migration logic: https://github.com/cosmos/cosmos-sdk/blob/master/x/staking/migrations/v046/store.go
