### ISSUE TITLE
Set up mergify in cosmos-sdk fork

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/cosmos-sdk#143]

**Comment by alexanderbez** [comment]
I think we already have mergify enabled -> https://github.com/osmosis-labs/cosmos-sdk/blob/v0.45.0x-osmo-v7/.mergify.yml

Is there an issue with the `automerge` label?

**Comment by p0mvn** [comment]
For the scope of this issue, we should:
- create a main/master branch and make it default
- enable backporting to v0.45.0x-osmo-v7 and earlier osmosis-SDK branches
- confirm if automerge is working
- adjust other configurations for our needs (currently they are inherited from upstream)

**Comment by alexanderbez** [comment]
I've done the following thus far:

- Updated and cleaned up labels
- Merged https://github.com/osmosis-labs/cosmos-sdk/pull/157
- Renamed `v0.45.0x-osmo-v7` -> `osmosis-main` (default branch)
- Branched a new `v0.45.0x-osmo-v7` branch off of `osmosis-main` for backporting
- Updated mergify config: https://github.com/osmosis-labs/cosmos-sdk/pull/168
