### ISSUE TITLE
GRPC server and client configuration might be too small

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/cosmos-sdk#169]
## Summary of Bug

Reported on Discord:
```
After updating some of nodes to 7.1.0 we started getting grpc errors from them when querying transactions
grpc: received message larger than max (4515191 vs. 4194304)
Never had that one before

sooo i had to edit grpc server and client configurations in cosmos sdk to increase the default cap of 4MB and rebuild osmosis binary

I've set it way higher at 20MB (just to be sure), didn't have any issues since then. Will report back if it happens again
```

This might be related to https://github.com/osmosis-labs/cosmos-sdk/pull/137
## Version
`v0.45.0x-osmo-v7` or `v7.1.0`

## Acceptance Criteria
- [ ] Investigate if the cap needs to be increased and to what value
- [ ] if should increase, make a PR with the change

**Comment by Krewedk0** [comment]
It was me to get this error while querying blocks transactions through REST.
One of the few blocks that threw this error was 3797259:
`curl -s 'localhost:1317/cosmos/tx/v1beta1/txs?events=tx.height=3797259&pagination.offset=0&pagination.limit=1000&pagination.count_total=false'`

**Comment by alexanderbez** [comment]
I think we can close this :)
