### ISSUE TITLE
gov.proto merged with conflicts

### ISSUE THREAD

**Issue by ant1g** [osmosis-labs/cosmos-sdk#259]
#### System information

Osmosis version: `v0.45.0x-osmo-v7`
OS & Version: Linux
Commit hash: 51108b6dcab2d134170265ec5a568c7c43d490f1

#### Expected behaviour
Osmosis currently depends on this committed version of the cosmos-sdk.
Osmosis proto generation should succeed.

#### Actual behaviour
It does not, because of proto file that was merged with conflicts, see here:
https://github.com/osmosis-labs/cosmos-sdk/commit/51108b6dcab2d134170265ec5a568c7c43d490f1#diff-11eba0a7e81d48edf4761a94648f1c916c18631ef389ba684bb33cbbaf250af0R201

#### Steps to reproduce the behaviour
Simply try to generate the Osmosis proto or start the Osmosis chain with ignite on `main` branch.

#### Backtrace

````
[STARPORT] cannot build app:
[STARPORT] 
[STARPORT] 	file: /home/johndoe/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220607221533-51108b6dcab2/proto/cosmos/gov/v1beta1/gov.proto: <input>:201:1: found "<" but expected [.proto element {comment|option|import|syntax|enum|service|package|message}]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by ant1g** [comment]
In addition, this was merged to the branch that is used to build osmosis v9.

**Comment by ant1g** [comment]
Anyone could look into this? AFAIK, this is blocking any build on osmosis v9 right now... I can attempt to fix it but I am not sure about the right way to resolve that conflict though. Thanks!

**Comment by ValarDragon** [comment]
yikes, cc @p0mvn

**Comment by ValarDragon** [comment]
I believe this got fixed! Thanks for reporting, please re-open if still an issue!
