### ISSUE TITLE
Make a CI action / label, that makes it easy to cherry-pick just a commit against cosmos SDK main

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/cosmos-sdk#268]
## Background
Lets get a mergify setup, that makes it easy for us to PR a commit against SDK main.

Would be great if possible to do with maintaining the Osmosis fork developer contribution info on SDK main, but I think we can figure that out secondarily.

## Suggested Design

Setup mergify in the fork to PR to SDK main

## Acceptance Criteria

Adding a label automatically opens a PR against SDK main

**Comment by ValarDragon** [comment]
Turns out mergify can't do PR's across forks :(

We just want something that does exactly what Mergify does, but PR to another fork.

@alexanderbez @ValarDragon @marbar3778 didn't find such a tool on quick look, but it surely has to exist? (Or is there a way to fork mergify to get in there?)

**Comment by alexanderbez** [comment]
I took a quick look and couldn't find anything. Honestly, I would just write a script and use a github action with a github token  to auto create PRs -- we also get credit this way too.

**Comment by xBalbinus** [comment]
Agreed! Sounds good to me.

**Comment by xBalbinus** [comment]
Slight latency on this due to some work on proto-correctness CI, heads up.

**Comment by xBalbinus** [comment]
May be closed by https://github.com/cosmos/cosmos-sdk/pull/12436; testing still needs to happen.

**Comment by xBalbinus** [comment]
Finished
