### ISSUE TITLE
how to create an AccAddress from a given private key

### ISSUE THREAD

**Issue by jinj** [osmosis-labs/cosmos-sdk#276]
I searched the repository but could not find any example. Where can I find the steps:
1. generate a private key
2. derive public from private key
3. derive address from public key
Thanks

**Comment by sunnya97** [comment]
What exactly are you trying to do?

You can see the steps that the Cosmos SDK uses for 2 and 3 here:  https://github.com/osmosis-labs/cosmos-sdk/blob/osmosis-main/crypto/keys/secp256k1/secp256k1_test.go#L37

For #1, you can use the this function:
https://github.com/osmosis-labs/cosmos-sdk/blob/osmosis-main/crypto/keys/secp256k1/secp256k1.go#L82

**Comment by sunnya97** [comment]
closing this.
