### ISSUE TITLE
new proto annotations exist upstream

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/cosmos-sdk#400]
[This PR](https://github.com/cosmos/cosmos-sdk/pull/13501) added amino annotations for codegen.

If we don't want to take the entire PR, I suggest we at least [add this proto file](https://github.com/cosmos/cosmos-sdk/tree/main/proto/amino)

[this PR in Osmosis](https://github.com/osmosis-labs/osmosis/pull/3782) depends on this issue

**Comment by faddat** [comment]
Okay you got it sir

**Comment by pyramation** [comment]
@faddat — can you cherry pick the annotations? I think @ValarDragon was suggesting we want to cherry pick only portions from https://github.com/cosmos/cosmos-sdk/pull/13501 

@ValarDragon can you describe what code we do and don't want from that PR?

**Comment by faddat** [comment]
totally.  I'll see what I can do rn

this?

https://github.com/cosmos/cosmos-sdk/commit/b49f948b36bc991db5be431607b475633aed697e

**Comment by pyramation** [comment]
> totally. I'll see what I can do rn
> 
> this?
> 
> [cosmos@b49f948](https://github.com/cosmos/cosmos-sdk/commit/b49f948b36bc991db5be431607b475633aed697e)

yea that one!

**Comment by mattverse** [comment]
Agreed with just taking amino.proto from the original PR!

**Comment by pyramation** [comment]
> Agreed with just taking amino.proto from the original PR!

@faddat so yea this should make it simple then ^^

**Comment by mattverse** [comment]
@pyramation Do you know if the new way of amino annotations is compatible with the current way of handling amino?

**Comment by pyramation** [comment]
> @pyramation Do you know if the new way of amino annotations is compatible with the current way of handling amino?

@mattverse there are no actual changes as far as functionality or Go is concerned. However, the annotations do enable us to  do many things after we have them in place!

**Comment by pyramation** [comment]
this is needed to use the new transpiler that will solve a ton of client side amino encoding for `google.protobuf.Any` types. Will be very useful for governance `MsgSubmitProposal`, as well as authz when 0.47 comes out — full amino support for any message!

Very useful also for RPC — e.g. pools and their types magically decoded!

cc @faddat @mattverse @ValarDragon 

Can we open this issue back up?
