### ISSUE TITLE
The `--is-expedited` flag for submit-proposal subcommand doesn't work

### ISSUE THREAD

**Issue by larry0x** [osmosis-labs/cosmos-sdk#433]
#### System information

Osmosis version: `15.0.0`
OS & Version: macOS
Commit hash: `ff18d8244fcda7313ec951fb1b3bee8369b8316b`

#### Expected behaviour

I just created mainnet prop 489 with the following command which specifies `--is-expedited false`:

```bash
osmosisd tx gov submit-proposal \
  --title "Set token creation fee to zero; introduce an alternative spam-prevention mechanism" \
  --description "$(cat workspace/proposal.md)" \
  --type Text \
  --deposit 1600000000uosmo \
  --is-expedited false \
  --from myaccount \
  --gas auto --gas-adjustment 1.4 --gas-prices 0.0025uosmo
```

#### Actual behaviour

A tx is generated with `"is_expedited": true`:

<img width="1061" alt="Screenshot 2023-04-20 at 09 54 42" src="https://user-images.githubusercontent.com/26318510/233238526-2a38c2a4-448e-4660-b4d2-87ead914696b.png">

My speculation is this has to do with `--is-expedited false` vs `--is-expedited=false`. Maybe using a space vs using an equal mark is different. Not sure.

**Comment by julienrbrt** [comment]
> My speculation is this has to do with --is-expedited false vs --is-expedited=false. Maybe using a space vs using an equal mark is different. 

Yes, you have to use `=` for boolean flags in cobra: https://github.com/spf13/cobra/issues/613

**Comment by ValarDragon** [comment]
wtf, thats crazy.

Perhaps, lets add an additional prompt for the user to confirm in the CLI then in the event that someone set an expedited prop ?
