### ISSUE TITLE
Upstreaming

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/cosmos-sdk#63]
@ValarDragon and I have had some conversations about upstreaming osmosis SDK changes into the mainline SDK.

Recently, I attempted with this commit:

https://github.com/osmosis-labs/cosmos-sdk/pull/58

the SDK has make a number of changes upstream, like how tests are done, that'll make this challenging.  I'm going to continue on it, basically as a learning exercise.

I am going to use this issue to track things, and don't really expect that it will be fast. I think that ideally, we need to either formally fork off, or figure out what features and changes are needed to mainline so that we can start using that.  

wdyt?

**Comment by sunnya97** [comment]
We should be taking specific commits/features from our rebased fork, and opening them as PRs to the mainline SDK
